# Generated by Django 5.1.15 on 2026-01-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriKarya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('deskripsi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kategori Karya',
                'verbose_name_plural': 'Kategori Karya',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Teknologi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Class icon atau URL', max_length=50)),
            ],
            options={
                'verbose_name': 'Teknologi',
                'verbose_name_plural': 'Teknologi',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='KaryaMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('jenis', models.CharField(choices=[('skripsi', 'Skripsi'), ('proyek', 'Proyek Akhir'), ('penelitian', 'Penelitian'), ('aplikasi', 'Aplikasi'), ('game', 'Game'), ('website', 'Website'), ('multimedia', 'Multimedia'), ('iot', 'IoT'), ('ai_ml', 'AI/Machine Learning'), ('vr_ar', 'VR/AR'), ('lainnya', 'Lainnya')], default='proyek', max_length=20)),
                ('nama_pembuat', models.CharField(max_length=200)),
                ('nim_pembuat', models.CharField(blank=True, max_length=20, verbose_name='NIM')),
                ('angkatan', models.CharField(blank=True, max_length=10)),
                ('foto_pembuat', models.ImageField(blank=True, upload_to='karya/pembuat/')),
                ('nama_pembimbing', models.CharField(blank=True, max_length=200)),
                ('deskripsi', models.TextField()),
                ('fitur', models.TextField(blank=True, help_text='Fitur utama, pisahkan dengan enter')),
                ('gambar_utama', models.ImageField(upload_to='karya/')),
                ('gambar_2', models.ImageField(blank=True, upload_to='karya/')),
                ('gambar_3', models.ImageField(blank=True, upload_to='karya/')),
                ('video_demo', models.URLField(blank=True, help_text='URL video demo (YouTube)')),
                ('link_demo', models.URLField(blank=True, help_text='Link ke demo/live preview')),
                ('link_github', models.URLField(blank=True, help_text='Link GitHub repository')),
                ('link_playstore', models.URLField(blank=True, help_text='Link Play Store')),
                ('link_download', models.URLField(blank=True, help_text='Link download')),
                ('tahun', models.IntegerField(verbose_name='Tahun Pembuatan')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Karya Unggulan')),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='karya.kategorikarya')),
                ('teknologi', models.ManyToManyField(blank=True, to='karya.teknologi')),
            ],
            options={
                'verbose_name': 'Karya Mahasiswa',
                'verbose_name_plural': 'Karya Mahasiswa',
                'ordering': ['-is_featured', '-tahun', '-created_at'],
            },
        ),
    ]
