# Generated by Django 5.1.15 on 2026-01-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('pendaftaran', 'Pendaftaran'), ('akademik', 'Akademik'), ('kurikulum', 'Kurikulum'), ('fasilitas', 'Fasilitas'), ('beasiswa', 'Beasiswa'), ('karir', 'Karir'), ('kontak', 'Kontak'), ('umum', 'Umum')], max_length=20)),
                ('pertanyaan', models.TextField(help_text='Pertanyaan atau kata kunci yang mungkin diajukan')),
                ('kata_kunci', models.TextField(help_text='Kata kunci terkait, pisahkan dengan koma')),
                ('jawaban', models.TextField()),
                ('link_terkait', models.URLField(blank=True, help_text='Link ke halaman terkait')),
                ('prioritas', models.IntegerField(default=0, help_text='Semakin tinggi, semakin diprioritaskan')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Base',
                'verbose_name_plural': 'Knowledge Base',
                'ordering': ['-prioritas', 'kategori'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sesi Chat',
                'verbose_name_plural': 'Sesi Chat',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.CharField(max_length=100)),
                ('urutan', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quick Reply',
                'verbose_name_plural': 'Quick Reply',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('matched_knowledge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_messages', to='chatbot.chatbotknowledge')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Pesan Chat',
                'verbose_name_plural': 'Pesan Chat',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Tidak Membantu'), (2, 'Kurang Membantu'), (3, 'Cukup Membantu'), (4, 'Membantu'), (5, 'Sangat Membantu')])),
                ('komentar', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot.chatmessage')),
            ],
            options={
                'verbose_name': 'Feedback Chatbot',
                'verbose_name_plural': 'Feedback Chatbot',
            },
        ),
    ]
