# Generated by Django 5.1.15 on 2026-01-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.CharField(max_length=500)),
                ('jawaban', models.TextField()),
                ('kategori', models.CharField(choices=[('akademik', 'Akademik'), ('pendaftaran', 'Pendaftaran'), ('beasiswa', 'Beasiswa'), ('fasilitas', 'Fasilitas'), ('karir', 'Karir'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('urutan', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0, verbose_name='Jumlah Dilihat')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Jumlah Terbantu')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['kategori', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='Kemitraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Mitra')),
                ('logo', models.ImageField(upload_to='kemitraan/', verbose_name='Logo Mitra')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi Kerjasama')),
                ('website', models.URLField(blank=True)),
                ('jenis_kerjasama', models.CharField(blank=True, max_length=100, verbose_name='Jenis Kerjasama')),
                ('tanggal_mulai', models.DateField(blank=True, null=True)),
                ('tanggal_berakhir', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('urutan', models.IntegerField(default=0, verbose_name='Urutan Tampil')),
            ],
            options={
                'verbose_name': 'Kemitraan',
                'verbose_name_plural': 'Kemitraan',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='PesanKontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subjek', models.CharField(max_length=200)),
                ('pesan', models.TextField()),
                ('status', models.CharField(choices=[('baru', 'Baru'), ('dibaca', 'Sudah Dibaca'), ('dibalas', 'Sudah Dibalas')], default='baru', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pesan Kontak',
                'verbose_name_plural': 'Pesan Kontak',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilProdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visi', models.TextField(verbose_name='Visi')),
                ('misi', models.TextField(help_text='Pisahkan setiap poin misi dengan enter baru', verbose_name='Misi')),
                ('tujuan', models.TextField(blank=True, verbose_name='Tujuan')),
                ('sejarah', models.TextField(blank=True, verbose_name='Sejarah')),
                ('nama_kaprodi', models.CharField(max_length=200, verbose_name='Nama Ketua Prodi')),
                ('foto_kaprodi', models.ImageField(blank=True, upload_to='profil/', verbose_name='Foto Kaprodi')),
                ('gelar_kaprodi', models.CharField(blank=True, max_length=100, verbose_name='Gelar')),
                ('sambutan_kaprodi', models.TextField(blank=True, verbose_name='Sambutan Kaprodi')),
                ('akreditasi', models.CharField(default='A', max_length=10, verbose_name='Akreditasi')),
                ('nomor_sk_akreditasi', models.CharField(blank=True, max_length=100, verbose_name='Nomor SK Akreditasi')),
                ('tanggal_akreditasi', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Program Studi',
                'verbose_name_plural': 'Profil Program Studi',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Program Studi Teknik Informatika', max_length=200)),
                ('site_tagline', models.CharField(default='Membangun Generasi Digital Indonesia', max_length=500)),
                ('site_description', models.TextField(blank=True)),
                ('university_name', models.CharField(default='Universitas Muhammadiyah Surakarta', max_length=200)),
                ('faculty_name', models.CharField(default='Fakultas Keguruan dan Ilmu Pendidikan', max_length=200)),
                ('address', models.TextField(default='Jl. A. Yani, Mendungan, Pabelan, Kec. Kartasura, Kabupaten Sukoharjo, Jawa Tengah 57162')),
                ('phone', models.CharField(default='(0271) 717417', max_length=20)),
                ('email', models.EmailField(default='pti@ums.ac.id', max_length=254)),
                ('instagram', models.URLField(blank=True, default='https://instagram.com/ptiums')),
                ('youtube', models.URLField(blank=True, default='https://youtube.com/@ptiums')),
                ('twitter', models.URLField(blank=True, default='https://twitter.com/ptiums')),
                ('tiktok', models.URLField(blank=True, default='https://tiktok.com/@ptiums')),
                ('logo', models.ImageField(blank=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, upload_to='site/')),
                ('hero_image', models.ImageField(blank=True, upload_to='site/')),
                ('meta_keywords', models.TextField(blank=True, help_text='Keywords untuk SEO, pisahkan dengan koma')),
                ('jumlah_mahasiswa_aktif', models.IntegerField(default=0)),
                ('jumlah_alumni', models.IntegerField(default=0)),
                ('jumlah_dosen', models.IntegerField(default=0)),
                ('jumlah_hak_cipta', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Website',
                'verbose_name_plural': 'Pengaturan Website',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('subjudul', models.CharField(blank=True, max_length=500)),
                ('gambar', models.ImageField(upload_to='slider/')),
                ('link', models.URLField(blank=True, help_text='URL tujuan saat slider diklik')),
                ('urutan', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='testimonial/')),
                ('tipe', models.CharField(choices=[('alumni', 'Alumni'), ('mahasiswa', 'Mahasiswa'), ('dosen', 'Dosen'), ('mitra', 'Mitra')], default='alumni', max_length=20)),
                ('angkatan', models.CharField(blank=True, help_text='Tahun angkatan, contoh: 2020', max_length=10)),
                ('pekerjaan', models.CharField(blank=True, help_text='Pekerjaan saat ini', max_length=200)),
                ('perusahaan', models.CharField(blank=True, max_length=200)),
                ('testimoni', models.TextField()),
                ('video_url', models.URLField(blank=True, help_text='Link video YouTube (opsional)')),
                ('rating', models.IntegerField(default=5, help_text='Rating 1-5')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tampilkan di Homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonial',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('page_url', models.URLField()),
                ('referrer', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log Pengunjung',
                'verbose_name_plural': 'Log Pengunjung',
                'ordering': ['-visited_at'],
            },
        ),
    ]
