# Generated by Django 5.1.15 on 2026-01-06 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriBerita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Class icon Bootstrap, contoh: bi-newspaper', max_length=50)),
                ('warna', models.CharField(default='primary', help_text='Class warna Bootstrap', max_length=20)),
            ],
            options={
                'verbose_name': 'Kategori Berita',
                'verbose_name_plural': 'Kategori Berita',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='TagBerita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tag Berita',
                'verbose_name_plural': 'Tag Berita',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('jenis', models.CharField(choices=[('berita', 'Berita'), ('informasi', 'Informasi'), ('pengumuman', 'Pengumuman'), ('agenda', 'Agenda')], default='berita', max_length=20)),
                ('ringkasan', models.TextField(blank=True, help_text='Ringkasan singkat untuk preview')),
                ('konten', models.TextField(help_text='Konten lengkap berita (mendukung HTML)')),
                ('gambar_utama', models.ImageField(blank=True, upload_to='berita/')),
                ('gambar_alt', models.CharField(blank=True, help_text='Alt text untuk gambar', max_length=200)),
                ('video_url', models.URLField(blank=True, help_text='URL video YouTube (opsional)')),
                ('tanggal_event', models.DateTimeField(blank=True, help_text='Untuk jenis Agenda', null=True)),
                ('lokasi_event', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=False, verbose_name='Dipublikasikan')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Berita Unggulan')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Pin di Atas')),
                ('view_count', models.IntegerField(default=0, verbose_name='Jumlah Dilihat')),
                ('share_count', models.IntegerField(default=0, verbose_name='Jumlah Dibagikan')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='berita.kategoriberita')),
                ('tags', models.ManyToManyField(blank=True, to='berita.tagberita')),
            ],
            options={
                'verbose_name': 'Berita',
                'verbose_name_plural': 'Berita',
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='GaleriBerita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='berita/galeri/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('urutan', models.IntegerField(default=0)),
                ('berita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeri', to='berita.berita')),
            ],
            options={
                'verbose_name': 'Galeri Berita',
                'verbose_name_plural': 'Galeri Berita',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='KomentarBerita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('komentar', models.TextField()),
                ('is_approved', models.BooleanField(default=False, verbose_name='Disetujui')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('berita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='berita.berita')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='berita.komentarberita')),
            ],
            options={
                'verbose_name': 'Komentar Berita',
                'verbose_name_plural': 'Komentar Berita',
                'ordering': ['-created_at'],
            },
        ),
    ]
