# Generated by Django 5.1.15 on 2026-01-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('nip', models.CharField(blank=True, max_length=50, verbose_name='NIP/NIDN')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(blank=True, upload_to='dosen/')),
                ('jabatan_fungsional', models.CharField(blank=True, choices=[('guru_besar', 'Guru Besar'), ('lektor_kepala', 'Lektor Kepala'), ('lektor', 'Lektor'), ('asisten_ahli', 'Asisten Ahli'), ('tenaga_pengajar', 'Tenaga Pengajar')], max_length=50)),
                ('gelar_depan', models.CharField(blank=True, max_length=50)),
                ('gelar_belakang', models.CharField(blank=True, max_length=100)),
                ('bidang_keahlian', models.CharField(blank=True, max_length=200)),
                ('pendidikan_s1', models.CharField(blank=True, max_length=200, verbose_name='Pendidikan S1')),
                ('pendidikan_s2', models.CharField(blank=True, max_length=200, verbose_name='Pendidikan S2')),
                ('pendidikan_s3', models.CharField(blank=True, max_length=200, verbose_name='Pendidikan S3')),
                ('bio', models.TextField(blank=True, verbose_name='Biografi')),
                ('research_interest', models.TextField(blank=True, verbose_name='Minat Penelitian')),
                ('google_scholar', models.URLField(blank=True, verbose_name='Google Scholar')),
                ('scopus', models.URLField(blank=True, verbose_name='Scopus')),
                ('sinta', models.URLField(blank=True, verbose_name='SINTA')),
                ('orcid', models.URLField(blank=True, verbose_name='ORCID')),
                ('website', models.URLField(blank=True, verbose_name='Website Pribadi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_kaprodi', models.BooleanField(default=False, verbose_name='Ketua Prodi')),
                ('urutan', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dosen',
                'verbose_name_plural': 'Dosen',
                'ordering': ['-is_kaprodi', 'urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(upload_to='fasilitas/')),
                ('kapasitas', models.CharField(blank=True, max_length=50)),
                ('lokasi', models.CharField(blank=True, max_length=200)),
                ('urutan', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fasilitas',
                'verbose_name_plural': 'Fasilitas',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Kurikulum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Kurikulum')),
                ('tahun', models.CharField(max_length=10, verbose_name='Tahun Kurikulum')),
                ('deskripsi', models.TextField(blank=True)),
                ('file_kurikulum', models.FileField(blank=True, upload_to='kurikulum/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kurikulum Aktif')),
            ],
            options={
                'verbose_name': 'Kurikulum',
                'verbose_name_plural': 'Kurikulum',
                'ordering': ['-tahun'],
            },
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, verbose_name='Kode MK')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Mata Kuliah')),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')])),
                ('sks_teori', models.IntegerField(default=0, verbose_name='SKS Teori')),
                ('sks_praktik', models.IntegerField(default=0, verbose_name='SKS Praktik')),
                ('jenis', models.CharField(choices=[('wajib', 'Wajib'), ('pilihan', 'Pilihan'), ('praktikum', 'Praktikum')], default='wajib', max_length=20)),
                ('deskripsi', models.TextField(blank=True)),
                ('capaian_pembelajaran', models.TextField(blank=True, verbose_name='Capaian Pembelajaran')),
                ('dosen_pengampu', models.ManyToManyField(blank=True, related_name='mata_kuliah_diampu', to='akademik.dosen')),
                ('kurikulum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_kuliah', to='akademik.kurikulum')),
                ('prasyarat', models.ManyToManyField(blank=True, related_name='prasyarat_untuk', to='akademik.matakuliah')),
            ],
            options={
                'verbose_name': 'Mata Kuliah',
                'verbose_name_plural': 'Mata Kuliah',
                'ordering': ['semester', 'kode'],
                'unique_together': {('kurikulum', 'kode')},
            },
        ),
        migrations.CreateModel(
            name='JadwalKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_aktif', models.CharField(help_text='Contoh: Gasal 2025/2026', max_length=20, verbose_name='Semester Aktif')),
                ('kelas', models.CharField(max_length=10)),
                ('hari', models.CharField(choices=[('senin', 'Senin'), ('selasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', 'Jumat'), ('sabtu', 'Sabtu')], max_length=10)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('ruangan', models.CharField(max_length=50)),
                ('kapasitas', models.IntegerField(default=40)),
                ('is_active', models.BooleanField(default=True)),
                ('dosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akademik.dosen')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='akademik.matakuliah')),
            ],
            options={
                'verbose_name': 'Jadwal Kuliah',
                'verbose_name_plural': 'Jadwal Kuliah',
                'ordering': ['hari', 'jam_mulai'],
            },
        ),
        migrations.CreateModel(
            name='Publikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=500)),
                ('penulis_text', models.TextField(help_text='Nama penulis lengkap, pisahkan dengan koma')),
                ('jenis', models.CharField(choices=[('jurnal_intl', 'Jurnal Internasional'), ('jurnal_nas', 'Jurnal Nasional'), ('konferensi_intl', 'Konferensi Internasional'), ('konferensi_nas', 'Konferensi Nasional'), ('buku', 'Buku'), ('book_chapter', 'Book Chapter'), ('hki', 'Hak Kekayaan Intelektual')], max_length=20)),
                ('nama_jurnal', models.CharField(blank=True, max_length=300, verbose_name='Nama Jurnal/Prosiding')),
                ('tahun', models.IntegerField()),
                ('volume', models.CharField(blank=True, max_length=20)),
                ('issue', models.CharField(blank=True, max_length=20)),
                ('halaman', models.CharField(blank=True, max_length=20)),
                ('doi', models.CharField(blank=True, max_length=200, verbose_name='DOI')),
                ('url', models.URLField(blank=True)),
                ('abstrak', models.TextField(blank=True)),
                ('is_indexed', models.BooleanField(default=False, verbose_name='Terindeks Scopus/WoS')),
                ('penulis', models.ManyToManyField(related_name='publikasi', to='akademik.dosen')),
            ],
            options={
                'verbose_name': 'Publikasi',
                'verbose_name_plural': 'Publikasi',
                'ordering': ['-tahun', 'judul'],
            },
        ),
        migrations.CreateModel(
            name='RisetGrup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(blank=True, upload_to='riset/')),
                ('is_active', models.BooleanField(default=True)),
                ('anggota', models.ManyToManyField(blank=True, related_name='riset_grup', to='akademik.dosen')),
                ('ketua', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ketua_riset_grup', to='akademik.dosen')),
            ],
            options={
                'verbose_name': 'Riset Grup',
                'verbose_name_plural': 'Riset Grup',
                'ordering': ['nama'],
            },
        ),
    ]
