# Generated by Django 5.1.15 on 2026-01-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risetgrup',
            name='fokus_riset',
            field=models.TextField(blank=True, help_text='Pisahkan setiap fokus dengan enter baru'),
        ),
    ]
