# Generated by Django 5.1.15 on 2026-01-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriPrestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Class icon Bootstrap', max_length=50)),
                ('warna', models.CharField(default='warning', max_length=20)),
            ],
            options={
                'verbose_name': 'Kategori Prestasi',
                'verbose_name_plural': 'Kategori Prestasi',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('jenis', models.CharField(choices=[('mahasiswa', 'Prestasi Mahasiswa'), ('dosen', 'Prestasi Dosen'), ('prodi', 'Prestasi Program Studi')], default='mahasiswa', max_length=20)),
                ('tingkat', models.CharField(choices=[('internasional', 'Internasional'), ('nasional', 'Nasional'), ('regional', 'Regional'), ('provinsi', 'Provinsi'), ('universitas', 'Universitas')], max_length=20)),
                ('peringkat', models.CharField(choices=[('juara_1', 'Juara 1 / Gold Medal'), ('juara_2', 'Juara 2 / Silver Medal'), ('juara_3', 'Juara 3 / Bronze Medal'), ('harapan_1', 'Harapan 1'), ('harapan_2', 'Harapan 2'), ('harapan_3', 'Harapan 3'), ('finalis', 'Finalis'), ('nominee', 'Nominee'), ('special_award', 'Special Award'), ('best_paper', 'Best Paper'), ('lainnya', 'Lainnya')], max_length=20)),
                ('deskripsi', models.TextField()),
                ('nama_kompetisi', models.CharField(max_length=300, verbose_name='Nama Kompetisi/Event')),
                ('penyelenggara', models.CharField(max_length=200)),
                ('lokasi', models.CharField(blank=True, max_length=200)),
                ('tanggal', models.DateField()),
                ('nama_peraih', models.TextField(help_text='Nama peraih prestasi, pisahkan dengan enter jika lebih dari satu')),
                ('foto_peraih', models.ImageField(blank=True, upload_to='prestasi/')),
                ('gambar', models.ImageField(blank=True, upload_to='prestasi/')),
                ('video_url', models.URLField(blank=True)),
                ('link_berita', models.URLField(blank=True, help_text='Link ke berita terkait')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tampilkan di Homepage')),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestasi.kategoriprestasi')),
            ],
            options={
                'verbose_name': 'Prestasi',
                'verbose_name_plural': 'Prestasi',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
    ]
